#!/bin/sh
# /etc/init.d/iotclnt

### BEGIN INIT INFO
# Provides:             iotclnt
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    IoT Client Node App
# Description:		IoT Client Node App start server on boot
### END INIT INFO

export PATH=$PATH:/usr/local/bin/node:/usr/local/bin/forever:/usr/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules
export HOME=/home/pi/iotclnt

case "$1" in
  start)
    forever -p /home/pi/iotclnt/.forever --sourceDir=/home/pi/iotclnt --workingDir=/home/pi/iotclnt --minUptime 5000 --spinSleepTime 2000 start client.js
    ;;
  stop)
    exec forever stopall
    ;;
  *)

  echo "Usage: /etc/init.d/iotclnt {start|stop}"
  exit 1
  ;;
esac
exit 0
